# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build_and_test:
    name: Build_And_Test

    runs-on: ubuntu-latest

    steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 23
              uses: actions/setup-java@v4
              with:
                java-version: '23'
                distribution: 'temurin'
                cache: maven

            - name: Cache Maven
              uses: actions/cache@v3
              with:
                path: ~/.m2
                key: ${{ runner.os }}-m2-${{ hashfiles('**pom.xml') }}
                restore-keys: ${{ runner.os }}-m2
      
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            
  push_to_main:
    runs-on: ubuntu-latest
    name: Push_To_Main
    needs: build_and_test
      
    steps:
           - uses: actions/checkout@v2
             with:
               token: ${{secrets.PAT}}
               ref: ${{ github.events.pull_request.head.sha }}
           - run: echo "Opening pull request to master..."
           - run: |
                git push 
                
